config/routes.rb
Rails.application.routes.draw do
  get 'books/index', to: 'books#index'
  get 'books/show/:id', to: 'books#show'
  get 'books/create', to: 'books#create'
  get 'books/update', to: 'books#update'
  get 'books/destroy', to: 'books#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'pages#index', as: 'home'
  get '/about', to: 'pages#about', as: 'about'

  get '/products', to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :setup_data

  def index
    render json: @data
  end

  def show
    #respond back with the book in json
    render json: @data[params[:id].to_i - 1]
  end

  def create
    #respond back with the created book in json
    new_book = {id: "#{@data.length}", title: "#{params[:name]}", author: "#{params[:writer]}"}
    @data.push(new_book)
    render json: new_book
  end

  def update
    #respond back with the updated book in json
    updated_book = {id: "#{params[:id]}", title: "#{params[:name]}", author: "#{params[:writer]}"}
    @data[params[:id].to_i - 1] = updated_book
    render json: updated_book
  end

  def destroy
    #respond back with the deleted book in json
    render json: @data.delete_at(params[:id].to_i - 1)
  
  end

  private
  def setup_data
    @data = [
      {id: "1", title: "Harry Potter", author: "J.K Rowling"},
      {id: "2", title: "Name of the wind", author: "Patrick Rothfuss"}
    ]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    layout "application"

    def
         index
        @name = 'mike'
    end
    def about
        @name = 'joe'
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = ["Toothbrush", "Sweater", "Waterbottle"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/setup_data.html.erb
<h1>Books#setup_data</h1>
<p>Find me in app/views/books/setup_data.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>ABOUT</h1>

<%= link_to  "Home", home_path %>

<%= render  "shared/say_hi", name: @name %>

app/views/pages/index.html.erb
<%= render  "shared/nav_bar" %>

<h1> HELLO WORLD </h1>

<%= render  "shared/say_hi", name: "mike" %>

app/views/products/index.html.erb
<%= render  "shared/nav_bar" %>


<h1> PRODUCTS WORLD </h1>

<ul>
    <% for product in @products %>
        <li><%= product %>
    <% end %>
</ul>

app/views/shared/_nav_bar.html.erb
<nav>
    <%= link_to  "about", about_path %>
    <%= link_to  "hom", home_path %>
</nav>

app/views/shared/_say_hi.html.erb
hello <%= name %>